import 'package:waste_management_app/screens/home/models/carousel_blog_model.dart';

List<CarouselBlogModel> blogList = [
  CarouselBlogModel(
    title: 'Waste Segregation',
    description:
        'Waste segregation is very important to keep our environment clean and healthy. It is the first step in the waste management process.',
    imagePath: 'assets/images/homeScreen/waste_dispose.svg',
  ),
  CarouselBlogModel(
    title: 'Impact of Waste on Environment',
    description:
        'Waste is a substance or object which is no longer useful to us. It is generated by human activity. Waste is generated in every sector of the economy. It is generated in the form of solid, liquid, and gas. Waste is generated in every sector of the economy. It is generated in the form of solid, liquid, and gas.',
    imagePath: 'assets/images/homeScreen/environment.svg',
  ),
  CarouselBlogModel(
    title: 'Waste Disposal Methods',
    description:
        'Waste disposal methods refer to the various ways in which waste is placed for disposal. The waste disposal methods are broadly classified into two types: traditional methods and modern methods. Traditional methods include burial, burning, and sea dumping. Modern methods include sanitary landfills, incineration, composting, and recycling.',
    imagePath: 'assets/images/homeScreen/dustbin.svg',
  ),
  CarouselBlogModel(
    title: 'Waste Management Hierarchy',
    description:
        'Waste management hierarchy is a concept that is used to classify waste management strategies according to their desirability in terms of waste minimization. The hierarchy is as follows: Prevention, Minimization, Reuse, Recycling, Energy Recovery, Disposal.',
    imagePath: 'assets/images/homeScreen/city.svg',
  ),
];
